export const allPopupData = {
  wheatProgram: {
    header: [
      "اسم الجهة",
      "اسم الباخرة",
      "بداية البرنامج",
      "نهاية البرنامج",
      "تاريخ الرحلة",
      "تصريح الافراج",
      "نوع الحجز",
      "نوع القمح",
      "الوزن بالطن",
    ],
    headerTypes: [
      "text",
      "text",
      "date",
      "date",
      "date",
      "number",
      "text",
      "text",
      "number",
    ],
  },
  millSessionsProgram: {
    header: [
      "اسم الجهة",
      "اسم الباخرة",
      "بداية البرنامج",
      "نهاية البرنامج",
      "تاريخ الرحلة",
      "تصريح الافراج",
      "نوع الحجز",
      "نوع القمح",
      "الوزن بالطن",
      "رقم الجلسة",
    ],
    headerTypes: [
      "text",
      "text",
      "date",
      "date",
      "date",
      "number",
      "text",
      "text",
      "number",
      "number",
    ],
  },
};
